feat: Homework2 Created a class for managing animals in zoo
SerhiiSokolov/go_course pull request #1
Opened 2024-08-10 17:45 UTC by Serhii-Sokolov-McK

2024-08-11 14:42 UTC, alexandear requested changes
Написав кілька зауважень, в цілому хороша робота.

Я би не ускладнював роботу циклами та складними конструкціями, ми це ще не проходили. Але хай вже будуть цикли.

Пропоную видалити більшість коментарів, бо вони не несуть додаткової цінності для читача. Їх підтримка та зміна в майбутньому обійдеться дорожче, ніж просто видалення зараз.

В загальному, коментар в коді залишають тоді, коли не зовсім зрозуміло, для чого цей рядок написаний. Тобто він має відповідати на запитання "Навіщо?" Але бувають і коментарі, які відповідають на питання "Що?" та "Як?" Ось тут деталі https://www.digitalocean.com/community/tutorials/how-to-write-comments-in-go

В умові задачі було "Звіри повтікали". Може додати ще можливість втікати звіру?

2024-08-11 14:42 UTC, alexandear commented on gocourse02/main.go
> +type Animal struct {
В загальному, я не прихильник коментарів, де й так дуже зрозумілий код. Але хай вже будуть.

Якщо вже лишати коментарі до структур та полів, то краще робити це по Go-шному. Ось тут детально розписано https://go.dev/doc/comment

Суть в тому, що перше слово має збігатись з назвою структури чи функції. Також наприкінці речення обов'язкова крапка:
```suggestion
// Animal represents an animal in a zoo.
type Animal struct {
```

2024-08-11 14:42 UTC, alexandear commented on gocourse02/main.go
> +	inTheCage bool   // Flag indicating whether the animal is in a cage
Неймінг - завжди суб'єктивна річ. Але я б перейменував так:
```suggestion
	isCaged bool   // Flag indicating whether the animal is in a cage
```

Зазвичай, але не завжди, `bool` змінні починаються з `is/if` префіксів.

2024-08-11 14:42 UTC, alexandear commented on gocourse02/main.go
> +type Zookeeper struct {
:memo: Якщо `zookeeper` - одне єдине слово, то ти написав правильно. Якщо два, то правильніше ось так:
```suggestion
type ZooKeeper struct {
```

2024-08-11 14:42 UTC, alexandear commented on gocourse02/main.go
> +	Animals []Animal // Slice of animals in the zoo
:memo: Ми slices не проходили, не обов'язково було робити.

Щодо коменту. Оскільки `Animals` - експортоване поле, то має бути так (вище лишив лінк на "Go Doc Comments"):

```suggestion
	Animals []Animal // Animals are animals in the zoo.
```

Або так:

```suggestion
	// Animals are animals in the zoo.
	Animals []Animal
```

2024-08-11 14:42 UTC, alexandear commented on gocourse02/main.go
> +		fmt.Println(err) // Print any error if animals couldn't be placed in cages
Я правильно розумію, що якщо наглядач не зможе додати тварину в клітку, то це нормально і програма не має перериватись?

Якщо так, то це треба прокоментувати в коді.

2024-08-11 14:42 UTC, alexandear commented on gocourse02/main.go
> +}
Всі ці коментарі зайві, тому що вони дублюють інструкції коду. Можна видаляти.

Краще додати один єдиний коментар до цілої функції. Щось типу:

```go
// AddAnimalToCage садить всіх звірів із зоопарку в клітки.
// Повертає nil, якщо тварина поміщена в клітку.
// Повертає помилку, якщо всі клітки зайняті і тварина не поміщена в клітку.
func (zk Zookeeper) AddAnimalToCage(c *AllCages, z *Zoo) error {
```

2024-08-11 14:42 UTC, alexandear commented on gocourse02/main.go
> +		if !animal.inTheCage {  // If the animal is not already in a cage
:memo: Ми поки не вчили `for` та `if`, не буду коментувати їх використання. Можна було не ускладнювати програму :)

2024-08-11 14:42 UTC, alexandear commented on gocourse02/main.go
> +		fmt.Println("Cage is empty!\n") // Print if the cage is empty
Ось ця інструкція додасть два переноси рядка. Суфікс `ln` один + `\n` ще один.  

Я думаю, що тут малось на увазі:

```suggestion
		fmt.Println("Cage is empty!")
```

або

```suggestion
		fmt.Printf("Cage is empty!\n")
```

Якщо дійсно треба два переноси рядка, то краще ось так:

```go
		fmt.Printf("Cage is empty!\n\n")
```

2024-08-11 14:42 UTC, alexandear commented on gocourse02/main.go
> +		fmt.Println("Cage is empty!\n") // Print if the cage is empty
Коментар `Print if the cage is empty` не потрібен, краще видалити.

2024-08-11 14:42 UTC, alexandear commented on gocourse02/main.go
> +func ReproduceAnimals(species string, name string) *Animal {
Як думаєш, можливість розмножуватись, це властивість тварини? Тобто чи не краще зробити метод `Reproduce` для `Animal`?

Використання буде по типу:

```go
lion := NewAnimal("lion", "Simba")
kion := lion.Reproduce("Kion")
```

Можна ще далі піти, для розмноження потрібно двоє тварин:

```
lion := NewAnimal("lion", "Simba")
nala := NewAnimal("lion", "Nala")

kion := lion.Reproduce(nala, "Kion") // в льва Simba та львиці Nala народилось дитинча Kion
```

2024-08-11 14:42 UTC, alexandear commented on gocourse02/main.go
> +	animal string // Species of the animal currently in the cage
А ми можемо тут замість назви тварини зберігати поінтер на тварину?

```suggestion
	animal *Animal // the animal currently in the cage
```

Поінтер буде `nil`, якщо клітка не зайнята.

2024-08-11 14:42 UTC, alexandear commented on gocourse02/main.go
> +func (c Cage) DescribeCage() {
Можна без "Cage", так трохи простіше:
```suggestion
func (c Cage) Describe() {
```

2024-08-11 15:02 UTC, alexandear commented on gocourse02/main.go
> +type Zookeeper struct {
Одне https://www.merriam-webster.com/dictionary/zookeeper

2024-08-11 15:34 UTC, SerhiiSokolov commented on gocourse02/main.go
> +type Animal struct {
Removed all comments

2024-08-11 15:37 UTC, SerhiiSokolov commented on gocourse02/main.go
> +	Animals []Animal // Slice of animals in the zoo
Я взагалі повидаляю ці коменти )

2024-08-11 15:48 UTC, SerhiiSokolov commented on gocourse02/main.go
> +		fmt.Println(err) // Print any error if animals couldn't be placed in cages
Додав коменти

2024-08-11 15:49 UTC, SerhiiSokolov commented on gocourse02/main.go
> +		fmt.Println("Cage is empty!\n") // Print if the cage is empty
Видалив і комент і \n

2024-08-11 15:52 UTC, SerhiiSokolov commented on gocourse02/main.go
> +	animal string // Species of the animal currently in the cage
Done

2024-08-11 16:01 UTC, SerhiiSokolov commented on gocourse02/main.go
> +func ReproduceAnimals(species string, name string) *Animal {
Додав таку властивість

2024-08-11 17:26 UTC, SerhiiSokolov commented
@alexandear Відповів на усі коменти, додав нові методи

2024-08-11 19:17 UTC, alexandear requested changes
Ще кілька зауважень, які пофіксити, і буде чудово.

2024-08-11 19:17 UTC, alexandear commented on gocourse02/main.go
> +	// Якщо усі клітки зайняті то це ок, і доглядач зоопарку має сам вирішити це питання
:memo: Коментарі в коді можна писати англійською. Це трішки полегшить тобі роботу, щоб не перемикати розкладки.

2024-08-11 19:17 UTC, alexandear commented on gocourse02/main.go
> +func NewCage(name string) *Cage {
Між методами, структурами та функціями краще додавати пустий рядок для полегшення читання:

```suggestion
}

func (a *Animal) Escape() {
	fmt.Printf("Animal %s escaped from the cage %v\n", a.name, a.cage.name)
	a.cage.animal = nil
	a.cage = nil
}

func NewCage(name string) *Cage {
```

Інколи методи не розділяються пустими рядками. Але це короткі однорядкові методи, які рідко зустрінеш. Наприклад, https://github.com/golang/go/blob/d36353499f673c89a267a489beb80133a14a75f9/src/cmd/compile/internal/ir/func.go#L188-L192

2024-08-11 19:17 UTC, alexandear commented on gocourse02/main.go
> +	species string
Може зробити для `species` константи? У нас же фіксовані значення.

Оголосити тип `type AnimalSpecies string`, який може мати значення:

```
const (
	Lion    AnimalSpecies = "lion"
	Warthog AnimalSpecies = "warthog"
	// other
)
``` 

Змінити всі методи та структури. Замість `species string` буде `species AnimalSpecies`. Це захистить від передачі довільного рядка в `species`.

2024-08-11 19:17 UTC, alexandear commented on gocourse02/main.go
> +func (zk Zookeeper) AddAnimalToCage(c *AllCages, z *Zoo) error {
Пропоную видалити структуру `AllCages`, вона не сильно корисна та ускладнює код. Перенести `Cages []Cage` в структуру `Zoo`. Ніби логічно, що зоопарк містить в собі звірів та клітки. 

Буде так:
```suggestion
func (zk Zookeeper) AddAnimalToCage(z *Zoo) error {
```

Можливо, навіть зоопарк містить в собі наглядача. Але це вже другорядне.

2024-08-11 19:17 UTC, alexandear commented on gocourse02/main.go
> +	return NewAnimal(species, name)
Думаю, що `species` не потрібно передавати в параметри. Бо ж ми можемо взяти його із ресівера `a`:
```suggestion
func (a Animal) Reproduce(name string) *Animal {
	return NewAnimal(a.Species, name)
```

2024-08-11 19:17 UTC, alexandear commented on gocourse02/main.go
> +
зайвий пустий рядок, краще видалити

2024-08-12 04:30 UTC, SerhiiSokolov commented on gocourse02/main.go
> +	// Якщо усі клітки зайняті то це ок, і доглядач зоопарку має сам вирішити це питання
Так ти надав приклад українською, я так і зробив ))

2024-08-15 09:56 UTC, Serhii-Sokolov-McK commented on gocourse02/main.go
> +	species string
Зробив, але щось я взагалі не зрозумів що це дає бо все одно можу зробити
```go
	simba := NewAnimal("asdkjhasd", "Simba")
	fmt.Println(simba.species)
	nala := NewAnimal(Lion, "Nala")
```

2024-08-15 10:30 UTC, alexandear commented on gocourse02/main.go
> +	species string
Так, чисті raw рядки типу `"asdkjhasd"` можемо передати, тому що цей рядок має тип `untyped string`.

Але якщо у нас є інші константи, то захистить:

```go
type Color string

const (
	Red     Color = "red"
	Yeallow Color = "yellow"
)

nala := NewAnimal(Lion, "Nala")  // скомпілюється
simba := NewAnimal(Red, "Simba") // помилка компіляції `cannot use Red (constant "red" of type Color) as Species value in argument to NewAnimal`
```

Деталі про константи https://go.dev/blog/constants

2024-08-15 10:33 UTC, alexandear approved these changes
LGTM

Можеш мерджити після однієї маленької зміни, яку залишив.

2024-08-15 10:33 UTC, alexandear commented on gocourse02/main.go
> +	fmt.Println(simba.species)
Повернімо назад, як було:
```suggestion
	simba := NewAnimal(Lion, "Simba")
```

2024-08-15 11:18 UTC, merged